env:
  data_size: '50000'
  test_data_id: generated-test-data
jobs:
  detect-regression:
    name: Detect Regression
    needs: generate-test-data
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4.2.1
      with:
        distribution: corretto
        java-version: 11
    - continue-on-error: true
      name: Checkout ion-java-benchmark-cli
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        path: ion-java-benchmark-cli
        ref: master
        repository: amazon-ion/ion-java-benchmark-cli
    - continue-on-error: true
      name: Checkout ion-java from the previous commit
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        path: baseline
        ref: ${{ github.base_ref }}
        submodules: recursive
    - continue-on-error: true
      name: Checkout ion-java from the new commit.
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        path: new
        ref: ${{ github.head_ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        submodules: recursive
    - continue-on-error: true
      name: Download test Ion Data from artifacts
      uses: actions/download-artifact@v4
      with:
        name: generated-test-data
        path: testData
    - continue-on-error: true
      name: Build ion-java from the base commit
      run: './gradlew clean publishToMavenLocal

        '
      working-directory: baseline
    - continue-on-error: true
      name: Benchmark ion-java from the base commit
      run: "mvn clean install\nmkdir /home/runner/work/ion-java/ion-java/benchmarkresults\n\
        java -jar target/ion-java-benchmark-cli-0.0.1-SNAPSHOT-jar-with-dependencies.jar\
        \ ${{matrix.usage-patterns}} -r ion -o /home/runner/work/ion-java/ion-java/benchmarkresults/before.ion\
        \ /home/runner/work/ion-java/ion-java/testData/${{matrix.test-data}}.10n \n"
      working-directory: ion-java-benchmark-cli
    - continue-on-error: true
      name: Build ion-java from the new commit
      run: './gradlew clean publishToMavenLocal

        '
      working-directory: new
    - continue-on-error: true
      name: Benchmark ion-java from the new commit
      run: 'mvn clean install

        java -jar target/ion-java-benchmark-cli-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        ${{matrix.usage-patterns}} -r ion -o /home/runner/work/ion-java/ion-java/benchmarkresults/after.ion
        /home/runner/work/ion-java/ion-java/testData/${{matrix.test-data}}.10n

        '
      working-directory: ion-java-benchmark-cli
    - continue-on-error: true
      name: Detect regression
      run: 'a=$(java -jar target/ion-java-benchmark-cli-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        compare --benchmark-result-previous /home/runner/work/ion-java/ion-java/benchmarkresults/before.ion
        --benchmark-result-new /home/runner/work/ion-java/ion-java/benchmarkresults/after.ion)

        if [ ! -z "$a" ]; then echo "${a}" >> $GITHUB_STEP_SUMMARY; exit 1; fi

        '
      working-directory: ion-java-benchmark-cli
    strategy:
      fail-fast: false
      matrix:
        test-data:
        - nestedStruct
        - nestedList
        - sexp
        - realWorldDataSchema01
        - realWorldDataSchema02
        - realWorldDataSchema03
        usage-patterns:
        - ' read --mode AverageTime --forks 3 --warmups 2 --iterations 10 --api streaming '
        - ' read --mode AverageTime --forks 3 --warmups 2 --iterations 10 --api dom '
        - ' write --mode AverageTime --forks 3 --warmups 2 --iterations 10 --api streaming
          --io-type buffer --ion-length-preallocation 1 '
        - ' write --mode AverageTime --forks 3 --warmups 2 --iterations 10 --api dom
          --io-type buffer --ion-length-preallocation 1 '
  generate-test-data:
    name: Generate Test Data
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ion-data-generator
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        ref: main
        repository: amazon-ion/ion-data-generator
    - continue-on-error: true
      name: Build ion-data-generator
      run: mvn clean install
    - continue-on-error: true
      env:
        jar_file: target/ion-data-generator-1.0-SNAPSHOT.jar
        schema_dir: tst/com/amazon/ion/workflow
      name: Generate test data
      run: 'mkdir -p testData

        for test in nestedStruct nestedList sexp realWorldDataSchema01 realWorldDataSchema02
        realWorldDataSchema03

        do

        java -jar $jar_file generate -S ${{env.data_size}} --input-ion-schema $schema_dir/${test}.isl
        testData/${test}.10n

        done

        '
    - continue-on-error: true
      name: Upload test Ion Data to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.test_data_id}}
        path: testData
name: Ion Java performance regression detector
on:
  repository_dispatch:
    types: trigger-ga___ion-java-performance-regression-detector.yml
permissions:
  contents: read
