jobs:
  ion-test-driver:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ion-java
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        path: ion-java
        ref: master
        repository: amazon-ion/ion-java
    - continue-on-error: true
      name: Checkout ion-test-driver
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        path: ion-test-driver
        ref: master
        repository: amazon-ion/ion-test-driver
    - continue-on-error: true
      name: Set up python3 env
      run: python3 -m venv ion-test-driver/venv && . ion-test-driver/venv/bin/activate
    - continue-on-error: true
      name: Pip install
      run: pip3 install -r ion-test-driver/requirements.txt && pip3 install -e ion-test-driver
    - continue-on-error: true
      name: Get main branch HEAD sha
      run: cd ion-java && echo `git rev-parse --short=7 HEAD` && echo "main=`git rev-parse
        --short=7 HEAD`" >> $GITHUB_ENV
    - continue-on-error: true
      name: Get current commit sha
      run: cd ion-java && echo `git rev-parse --short=7 ${{ github.event.pull_request.head.sha
        }}` && echo "cur=`git rev-parse --short=7 ${{ github.event.pull_request.head.sha
        }}`" >> $GITHUB_ENV
    - continue-on-error: true
      name: Run ion-test-driver
      run: python3 ion-test-driver/amazon/iontest/ion_test_driver.py -o output -i
        ion-java,${{ github.event.pull_request.head.repo.html_url }},${{ github.event.pull_request.head.sha
        }} --replace ion-java,https://github.com/amazon-ion/ion-java.git,$main
    - continue-on-error: true
      name: Upload result
      uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595
      with:
        name: ion-test-driver-result.ion
        path: output/results/ion-test-driver-results.ion
    - continue-on-error: true
      name: showing result
      run: cat output/results/ion-test-driver-results.ion
    - continue-on-error: true
      id: result-diff
      name: Analyze two implementations
      run: python3 ion-test-driver/amazon/iontest/ion_test_driver.py -R ion-java,$main
        ion-java,$cur output/results/ion-test-driver-results.ion
    - continue-on-error: true
      name: Upload analysis report
      uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595
      with:
        name: analysis-report.ion
        path: result.ion
    - continue-on-error: true
      name: showing report
      run: cat result.ion
    - continue-on-error: true
      if: ${{ steps.result-diff.outcome == 'failure' }}
      name: Check if ion-test-driver fails
      run: echo 'Implementation behavior changed, Refer to the analysis report in
        the previous step for the reason.' && exit 1
  open-issue:
    if: ${{ failure() }}
    needs: ion-test-driver
    permissions:
      contents: read
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      name: Open an issue
      uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
      with:
        assignees: ${{ github.event.sender.login }}
        filename: .github/ion-test-driver-issue.md
name: ion-test-driver
on:
  repository_dispatch:
    types: trigger-ga___ion-test-driver.yml
permissions:
  contents: read
