jobs:
  check-version:
    name: Check Project Version
    outputs:
      should_create_draft: ${{ steps.inspect.outputs.is_valid_to_release }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Get project version
      run: 'echo "PROJECT_VERSION=$(<project.version)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: inspect
      uses: ./.github/actions/inspect-version
      with:
        project_version: ${{ env.PROJECT_VERSION }}
        repo: amazon-ion/ion-java
    - continue-on-error: true
      run: 'echo "Result: ${{ toJSON(steps.inspect.outputs) }}"

        '
  create-draft:
    if: ${{ needs.check-version.outputs.should_create_draft == 'true' }}
    name: Create Draft
    needs: check-version
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create a draft release
      run: 'echo "valid to release: ${{ needs.check-version.steps.inspect.outputs.is_valid_to_release
        }}"

        RELEASE_TAG="v$(<project.version)"

        # This intentionally creates the draft release in the current repo, which

        # could be a fork, if this workflow was triggered in a fork.

        gh release create "$RELEASE_TAG" --draft --generate-notes

        '
      shell: bash
name: Prepare Release
on:
  repository_dispatch:
    types: trigger-ga___prepare-release.yml
permissions: read-all
