jobs:
  check-tag:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Validate project version matches tag
      run: 'RELEASE_TAG=${GITHUB_REF#refs/tags/}

        # the tag should start with `v`, so prepend `v` to the contents of project.version

        PROJECT_VERSION="v$(<project.version)"

        echo "Project Version: $PROJECT_VERSION"

        echo "Release Tag: $RELEASE_TAG"

        [ "$PROJECT_VERSION" = "$RELEASE_TAG" ] || exit 1

        '
      shell: bash
  publish-to-github-release:
    needs: check-tag
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        submodules: recursive
    - continue-on-error: true
      uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e
      with:
        arguments: build cyclonedxBom
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload Jar to GitHub release
      run: 'gh release upload "v$(<project.version)" "build/libs/ion-java-$(<project.version).jar"

        gh release upload "v$(<project.version)" "build/reports/bom.json"

        '
name: Publish Artifacts for Release
on:
  repository_dispatch:
    types: trigger-ga___publish-release-artifacts.yml
permissions:
  contents: read
