jobs:
  run-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: inspect
      name: Invoke Action
      uses: ./.github/actions/inspect-version
      with:
        fail_if_invalid: ${{ matrix.fail_if_invalid }}
        project_version: ${{ matrix.version }}
        repo: amazon-ion/ion-java
    - continue-on-error: true
      if: ${{ matrix.expected == 'action_failure' }}
      name: Check For Expected Error
      run: 'PASS=${{ steps.test_fail.outcome != ''failure'' }}

        if [[ $PASS == ''false'' ]]; then exit 1; fi

        '
      shell: bash
    - continue-on-error: true
      env:
        PASS: "${{ \n  matrix.expected.is_newest == steps.inspect.outputs.is_newest\
          \ \n    && matrix.expected.is_release == steps.inspect.outputs.is_release\
          \ \n    && matrix.expected.is_valid_to_release == steps.inspect.outputs.is_valid_to_release\
          \ \n}}\n"
      if: ${{ matrix.expected != 'action_failure' }}
      name: Check For Expected Output
      run: 'echo "Pass? $PASS"

        echo "expected: ${{ toJSON(matrix.expected) }}"

        echo "was: ${{ toJSON(steps.inspect.outputs) }}"

        if [[ $PASS == ''false'' ]]; then exit 1; fi

        '
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
        - expected:
            is_newest: false
            is_release: true
            is_valid_to_release: false
          version: 1.0.0
        - expected: action_failure
          fail_if_invalid: true
          version: 1.0.0
        - expected:
            is_newest: false
            is_release: true
            is_valid_to_release: false
          version: v1.0.0
        - expected:
            is_newest: true
            is_release: true
            is_valid_to_release: true
          fail_if_invalid: true
          version: 3.0.0
        - expected:
            is_newest: true
            is_release: true
            is_valid_to_release: true
          version: v3.0.0
        - expected:
            is_newest: false
            is_release: false
            is_valid_to_release: false
          fail_if_invalid: true
          version: 1.0.0-SNAPSHOT
        - expected:
            is_newest: false
            is_release: false
            is_valid_to_release: false
          version: v1.0.0-SNAPSHOT
        - expected: action_failure
          version: nonsense_version
name: Test 'inspect-version' Action
on:
  repository_dispatch:
    types: trigger-ga___test-inspect-version-action.yml
permissions: read-all
